const PDFDocument = require('pdfkit');

const generatePDF = (req, res) => {
  const { target, time, findings } = req.body;

  if (!target || !findings) {
    return res.status(400).json({ error: "Missing report data" });
  }

  try {
    const doc = new PDFDocument({ margin: 50 });

    // Stream the PDF to the response
    // Vercel Serverless Requirement: Explicitly end response when stream finishes
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=sentrix-report-${Date.now()}.pdf`);
    
    // Create a Promise to handle the stream completion
    // This prevents the serverless function from timing out or freezing before the stream is done
    return new Promise((resolve, reject) => {
      doc.pipe(res);

      doc.on('end', () => {
        resolve();
      });

      doc.on('error', (err) => {
        reject(err);
      });

      // ---------------- HEADER ----------------
      doc.fontSize(20).text('SENTRIX Scan Report', { align: 'center' });
      doc.moveDown();
      
      doc.fontSize(12).text(`Target: ${target}`);
      doc.text(`Scan Date: ${new Date(time).toLocaleString()}`);
      doc.text(`Total Findings: ${findings.length}`);
      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke(); // Horizontal line
      doc.moveDown();

      // ---------------- FINDINGS ----------------
      if (findings.length === 0) {
        doc.fontSize(14).fillColor('green').text('✅ No vulnerabilities found. Great job!', { align: 'center' });
      } else {
        findings.forEach((finding, index) => {
          // Check if we need a new page to avoid cutting off content
          if (doc.y > 700) doc.addPage();

          const isCritical = finding.severity.toLowerCase() === 'critical' || finding.severity.toLowerCase() === 'high';
          
          doc.fontSize(14).fillColor(isCritical ? 'red' : 'black').text(`${index + 1}. ${finding.title}`, { underline: true });
          doc.fontSize(10).fillColor('black');
          
          doc.text(`Severity: ${finding.severity}`);
          doc.text(`Type: ${finding.type || 'General'}`);
          doc.text(`URL: ${finding.url || 'N/A'}`);
          doc.moveDown(0.5);
          
          doc.font('Helvetica-Bold').text('Detail:');
          doc.font('Helvetica').text(finding.detail || 'No details provided.');
          doc.moveDown(0.5);
          
          doc.font('Helvetica-Bold').text('Impact:');
          doc.font('Helvetica').text(finding.impact || 'No impact provided.');
          doc.moveDown(0.5);
          
          doc.font('Helvetica-Bold').text('Remediation:');
          doc.font('Helvetica').text(finding.fix || 'No fix provided.');
          
          doc.moveDown(1.5);
        });
      }

      // ---------------- FOOTER ----------------
      doc.addPage();
      doc.fontSize(10).text('Generated by Sentrix Security Scanner', { align: 'center', valign: 'bottom' });

      doc.end();
    });

  } catch (error) {
    console.error("PDF Generation Error:", error);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
};

module.exports = { generatePDF };